---
name: Rust

"on":
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies (Ubuntu)
        run: sudo apt install clang llvm pkg-config nettle-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install dependencies (macOS)
        run: brew install nettle
        if: matrix.os == 'macos-latest'
      - name: Build
        run: cargo build --verbose
      - name: Build with no default features
        run: cargo build --no-default-features --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with all features
        run: cargo test --all-features --verbose
        if: matrix.os != 'windows-latest'
      - name: Run tests with linebased feature only
        run: cargo test --no-default-features --features linebased --verbose
      - name: Run tests with deb822 feature only
        run: cargo test --no-default-features --features deb822 --verbose

  minimal-versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install cargo-minimal-versions
        run: cargo install cargo-minimal-versions cargo-hack
      - name: Test with minimal versions
        run: cargo minimal-versions test --verbose
